#!/bin/bash

# Check if code is installed
if ! command -v code &> /dev/null; then
    zenity --error --text="VSCode" "code could not be found. Please install it to use this script."
    exit 1
fi

code --new-window "$@"
