#!/bin/bash

file="$1"
line_to_add="$2"

# Check if the last character of the file is a newline
last_char
last_char=$(tail -c 1 "$file" 2>/dev/null)

if [ "$last_char" != "" ] && [ "$last_char" != $'\n' ]; then
    # If not a newline, add a newline before the new line
    echo -e "\n$line_to_add" >>"$file"
else
    # Otherwise, just append the line
    echo "$line_to_add" >>"$file"
fi