#!/bin/bash

# Define the name of the virtual environment
VENV_DIR="./.venv"

# Check if the virtual environment directory exists
if [ ! -d "$VENV_DIR" ]; then
    # If not exists, create a new virtual environment
    python3 -m venv "$VENV_DIR"
    echo "Created new virtual environment."
fi

# Activate the virtual environment
source "$VENV_DIR/bin/activate"