#!/bin/bash

# Sample usage:
#     try "command" num_of_try delay_on_error
#     try "command $input1 $input2" 5 3

input_command="$1"
if [ -z "$input_command" ]; then
  echo "$(basename "$0"): Input command is required."
  exit 1
fi

max_retries="$2"
if [ -z "$max_retries" ]; then
  max_retries=3
fi

delay_on_error="$3"
if [ -z "$delay_on_error" ]; then
  delay_on_error=3
fi

# Initialize a counter for retries
retries=0

# Loop until successful or max retries reached
while true; do
  # Run the gh repo clone command and capture the exit code
  eval "$input_command"
  exit_code=$?

  # Check if the exit code indicates an error
  if [ $exit_code -ne 0 ]; then
    echo -n "$app_name: Error encountered. "
    retries=$((retries + 1))

    # Check if we've reached the maximum number of retries
    if [ $retries -ge $max_retries ]; then
      echo "Maximum number of retries reached. Exiting."
      break
    fi

    echo "Retrying after $delay_on_error seconds..."
    sleep "$delay_on_error"
  else
    break # Exit the loop if successful
  fi
done